openapi: 3.0.0
info:
  title: Academic Chatbot API
  version: 1.0.0
paths:
  /api/chat:
    post:
      summary: Handle chat messages
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                message:
                  type: string
      responses:
        '200':
          description: Successful Response
        '400':
          description: Error occurred
